# Background and foreground colors
background = #060507
foreground = #F8EAC4

# Standard colors
palette = 0=#060507
palette = 1=#ab6f66
palette = 2=#8f7446
palette = 3=#ebd39e
palette = 4=#6e8bcc
palette = 5=#a06864
palette = 6=#6379aa
palette = 7=#F8EAC4

# Bright colors
palette = 8=#6a676d
palette = 9=#d69185
palette = 10=#b6985b
palette = 11=#ffdf7e
palette = 12=#90aeff
palette = 13=#ca8a84
palette = 14=#859cdb
palette = 15=#ffeb9e
