$color = rgba(6, 5, 7, 1)
$inner_color = rgba(6, 5, 7, 0.66)
$outer_color = rgba(160, 104, 100, 1)
$font_color = rgba(248, 234, 196, 1)
$placeholder_color = rgba(248, 234, 196, 0.7)
$check_color = rgba(99, 121, 170, 1)
