$color = rgba(246, 239, 224, 1)
$inner_color = rgba(246, 239, 224, 0.66)
$outer_color = rgba(142, 74, 72, 1)
$font_color = rgba(43, 36, 28, 1)
$placeholder_color = rgba(43, 36, 28, 0.7)
$check_color = rgba(74, 98, 140, 1)
