background            #f0e4c8
foreground            #2A2218

# black
color0  #f0e4c8
color8  #7a6a58

# red
color1  #a83228
color9  #c44a3c

# green
color2  #5a6434
color10 #6e7a40

# yellow
color3  #9a6b14
color11 #b8861e

# blue
color4  #6b2c58
color12 #8a4a72

# magenta
color5  #7a2e5a
color13 #9a4a72

#cyan
color6  #3d6b62
color14 #4e8a7a

#white
color7  #2A2218
color15 #1a140f


