background            #060507
foreground            #F8EAC4

# black
color0  #060507
color8  #6a676d

# red
color1  #ab6f66
color9  #d69185

# green
color2  #8f7446
color10 #b6985b

# yellow
color3  #ebd39e
color11 #ffdf7e

# blue
color4  #6e8bcc
color12 #90aeff

# magenta
color5  #a06864
color13 #ca8a84

#cyan
color6  #6379aa
color14 #859cdb

#white
color7  #F8EAC4
color15 #ffeb9e


