background            #f6efe0
foreground            #2B241C

# black
color0  #f6efe0
color8  #7a7166

# red
color1  #a14b42
color9  #c45c52

# green
color2  #6e5a32
color10 #8a7040

# yellow
color3  #8a5f12
color11 #926318

# blue
color4  #3d5c9a
color12 #5274b8

# magenta
color5  #8e4a48
color13 #a85c58

#cyan
color6  #4a628c
color14 #5c78a8

#white
color7  #2B241C
color15 #1a1612


